parameters:
#    haphan_localhop.example.class: Haphan\LocalhopBundle\Example

services:
#    haphan_localhop.example:
#        class: %haphan_localhop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
